name: static check
on:
  push:
    branches: main

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports

  errcheck:
    name: Errcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: errcheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: lint

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow

  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: staticcheck

  sec:
    name: Sec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: sec
          flags: "-exclude=G104"
